export const CATEGORY_CHANGED = 'CATEGORY_CHANGED';
export const CATEGORIES_LOADING_SUCCES = 'CATEGORIES_LOADING_SUCCES';
export const CATEGORIES_LOADING_FAIL = 'CATEGORIES_LOADING_FAIL';
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';

export const QUESTIONS_LOADING_SUCCESS = 'QUESTIONS_LOADING_SUCCESS';
export const QUESTIONS_LOADING_FAIL = 'QUESTIONS_LOADING_FAIL';
export const QUESTIONS_LOADING = 'QUESTIONS_LOADING';

export const REQUEST_TOKEN = 'REQUEST_TOKEN';
export const REQUEST_TOKEN_SUCCESS = 'REQUEST_TOKEN_SUCCESS';
export const REQUEST_TOKEN_FAIL = 'REQUEST_TOKEN_FAIL';

export const CALCULATE_RESULT = 'CALCULATE_RESULT';
export const CALCULATE_SUCCESS = 'CALCULATE_SUCCESS';

export const RESET_TOKEN = 'RESET_TOKEN';
export const RESET_SCORE = 'RESET_SCORE';
export const START_TIMER = 'START_TIMER';

export const ANSWER_OPTIONS = 'ANSWER_OPTIONS';
export const ANSWER_OPTION_1_CHANGED = 'ANSWER_OPTION_1_CHANGED';
export const ANSWER_OPTION_2_CHANGED = 'ANSWER_OPTION_2_CHANGED';
export const ANSWER_OPTION_3_CHANGED = 'ANSWER_OPTION_3_CHANGED';
export const ANSWER_OPTION_4_CHANGED = 'ANSWER_OPTION_4_CHANGED';
export const ANSWER_OPTION_5_CHANGED = 'ANSWER_OPTION_5_CHANGED';
export const ANSWER_OPTION_6_CHANGED = 'ANSWER_OPTION_6_CHANGED';
export const ANSWER_OPTION_7_CHANGED = 'ANSWER_OPTION_7_CHANGED';
export const ANSWER_OPTION_8_CHANGED = 'ANSWER_OPTION_8_CHANGED';
export const ANSWER_OPTION_9_CHANGED = 'ANSWER_OPTION_9_CHANGED';
export const ANSWER_OPTION_10_CHANGED = 'ANSWER_OPTION_10_CHANGED';
